### ISSUE TITLE
DBPedia Lookup build breaks with Java 8

### ISSUE THREAD

**Issue by mark-watson** [dbpedia/lookup#32] opened 2016-05-24 16:41 UTC
I tried changing the Scala version in the POM file, to no avail.

I tried building the master branch with Java 8 - worked until the end, with a "error: File name too long" error.

I understand that this is probably a low priority thing to fix, since people installing Java 7 is a good option.

EDIT: building master branch of the required extraction-framework works fine if I use an external non-encrypted drive and Java 8. Apparently having my home drive on Ubuntu encrypted caused the long file name error. I still can't build lookup: nxparser not found.

**Comment by jimkont** [comment] 2016-05-27 06:29
Travis says java8 works fine: https://travis-ci.org/dbpedia/lookup
so I am closing this as it looks related to local settings

**Closed by jimkont** 2016-05-27 06:29 UTC

**Comment by sandroacoelho** [comment] 2016-05-27 22:38
Hi @mark-watson: the problem is not with Java 8. The cause is that. http://nxparser.googlecode.com/svn/repository does not exist anymore. 

I've replaced it for a repo at github. Could you please try to recompile?

Best

**Comment by mark-watson** [comment] 2016-05-28 21:36
Thanks sandroacoelho,

That fixed it.
